language: scala

scala:
   - 2.12.2

services:
  - docker

script:
  - sbt compile
  - sbt clean coverage test coverageReport && sbt coverageAggregate

# see also https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - openssl aes-256-cbc -d -K $ENC_KEY -iv $ENC_IV -in project/gnupg/signkey.asc.enc -out project/gnupg/signkey.asc

after_success:
  - sbt coveralls

deploy:
  provider: script
  skip_cleanup: true
  script: sbt publishSigned
  on:
    tags: true
    branch: master